(define (fringe tree)
    (if (null? tree)
        '()
        (if (not (pair? tree))
            (list tree)
            (append (fringe (car tree))
                    (fringe (cdr tree))
            )
        )
    )
)