(load "product.ss")

(define (factorial n)
    (define (identity x) x)
    (define (next k) (+ k 1))
    (product identity 1 next n)
)

(define (pi n)
    (define (odd-square k) 
        (define odd-number (+ (* 2 k) 1))
        (/ 1 (* odd-number odd-number))
    )
    (define (term k) 
        (- 1 (odd-square k))
    )
    (define (next k) 
        (+ 1 k)
    )
    (* 4.0 (product term 1 next n))
)