(load "sum.ss")

(define (simpson f a b n)
    (define h (/ (- b a) n))
    (define (y k) (f (+ a (* k h))))
    (define (term k)
        (cond ((or (= k 0) (= k n)) (y k))
              ((even? k) (* 2 (y k)))
              (else (* 4 (y k)))
        )
    )
    (define (next k) (+ k 1))

    (* (/ h 3.0) (sum term 0 next n))
)